language: node_js

node_js:
    - "16.13.1"

branches:
    only:
        - master
cache:
    directories:
        - "$HOME/node_modules"

before_install:
    - yarn install

script:
    - yarn build

notifications:
    email:
        recipients:
            - freejak5520@naver.com
